# Generated by Django 5.2.7 on 2025-10-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryReport',
            fields=[
            ],
            options={
                'verbose_name': 'Territory Report',
                'verbose_name_plural': 'Territory Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('distribution.publication',),
        ),
    ]
