# Generated by Django 5.2.7 on 2025-10-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name (for Physical Persons)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name (for Physical Persons)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ownership/royalty share percentage', max_digits=5, null=True),
        ),
    ]
