# Generated by Django 5.2.7 on 2025-10-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_entity_first_name_entity_last_name_entity_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch/location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='nationality',
            field=models.CharField(blank=True, help_text='Country of origin/nationality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='stage_name',
            field=models.CharField(blank=True, help_text='Stage/professional name for artists', max_length=255, null=True),
        ),
    ]
