# Generated by Django 5.2.7 on 2025-10-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_entity_bank_branch_entity_bank_name_entity_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='shares',
        ),
    ]
