# Generated by Django 5.2.7 on 2025-10-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_remove_entity_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrole',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('producer', 'Producer'), ('composer', 'Composer'), ('lyricist', 'Lyricist'), ('audio_editor', 'Audio Editor'), ('label', 'Label'), ('booking', 'Booking'), ('endorsements', 'Endorsements'), ('publishing', 'Publishing'), ('productie', 'Productie'), ('new_business', 'New Business'), ('digital', 'Digital'), ('companie', 'Companie')], db_index=True, max_length=50),
        ),
    ]
