# Generated by Django 5.2.7 on 2025-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_remove_companie_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender (for Physical Persons)', max_length=1, null=True),
        ),
    ]
