# Generated by Django 5.2.7 on 2025-10-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_add_gender_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrole',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('producer', 'Producer'), ('composer', 'Composer'), ('lyricist', 'Lyricist'), ('audio_editor', 'Audio Editor'), ('client', 'Client'), ('brand', 'Brand'), ('label', 'Label'), ('booking', 'Booking'), ('endorsements', 'Endorsements'), ('publishing', 'Publishing'), ('productie', 'Productie'), ('new_business', 'New Business'), ('digital', 'Digital')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('soundcloud', 'SoundCloud'), ('bandcamp', 'Bandcamp'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], db_index=True, help_text='Social media platform', max_length=50)),
                ('handle', models.CharField(blank=True, help_text='Username/handle (without @ symbol)', max_length=255)),
                ('url', models.URLField(help_text='Full URL to the profile/page', max_length=500)),
                ('display_name', models.CharField(blank=True, help_text='Display name on the platform', max_length=255)),
                ('follower_count', models.IntegerField(blank=True, help_text='Number of followers/subscribers (optional)', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Is this account verified on the platform?')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary account for this platform?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='identity.entity')),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'ordering': ['platform', '-is_primary', '-follower_count'],
                'indexes': [models.Index(fields=['entity', 'platform'], name='identity_so_entity__2488ad_idx'), models.Index(fields=['platform', 'is_primary'], name='identity_so_platfor_6b9908_idx')],
            },
        ),
    ]
