# Generated by Django 5.2.7 on 2025-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_contactperson_contactemail_contactphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveidentity',
            name='_passport_number_encrypted',
            field=models.CharField(blank=True, help_text='Encrypted passport number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensitiveidentity',
            name='identification_type',
            field=models.CharField(choices=[('ID_CARD', 'Romanian ID Card'), ('PASSPORT', 'Passport')], default='ID_CARD', help_text='Type of identification document', max_length=20),
        ),
        migrations.AddField(
            model_name='sensitiveidentity',
            name='passport_country',
            field=models.CharField(blank=True, help_text='Country of passport issuance', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitiveidentity',
            name='_cnp_encrypted',
            field=models.CharField(blank=True, help_text='Encrypted CNP (for ID card)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensitiveidentity',
            name='id_issued_by',
            field=models.CharField(blank=True, help_text='Issuing authority', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensitiveidentity',
            name='id_series',
            field=models.CharField(blank=True, help_text="ID card series (e.g., 'RT')", max_length=10, null=True),
        ),
    ]
