# Generated by Django 5.2.7 on 2025-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_sensitiveidentity__passport_number_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogsensitive',
            name='field',
            field=models.CharField(choices=[('cnp', 'CNP'), ('passport_number', 'Passport Number'), ('ssn', 'SSN'), ('id_card', 'ID Card Details'), ('bank_account', 'Bank Account')], max_length=20),
        ),
    ]
