# Generated by Django 5.2.7 on 2025-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_alter_auditlogsensitive_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensitiveidentity',
            options={'permissions': [('reveal_sensitive_identity', 'Can reveal sensitive identity information')], 'verbose_name': 'Sensitive Identity', 'verbose_name_plural': 'Sensitive Identities'},
        ),
        migrations.CreateModel(
            name='SensitiveAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, help_text='Department code (e.g., legal, finance, digital)', max_length=50)),
                ('role', models.CharField(db_index=True, help_text='Role code within the department (e.g., manager, employee)', max_length=50)),
                ('field', models.CharField(choices=[('cnp', 'CNP')], db_index=True, help_text='Sensitive field governed by this policy', max_length=20)),
                ('can_reveal', models.BooleanField(default=True, help_text='Whether this department+role can reveal the field')),
                ('updated_by', models.CharField(blank=True, help_text='Operator identifier (email/name) who last edited the policy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensitive Access Policy',
                'verbose_name_plural': 'Sensitive Access Policies',
                'indexes': [models.Index(fields=['department', 'role', 'field'], name='identity_se_departm_53ce5b_idx')],
                'unique_together': {('department', 'role', 'field')},
            },
        ),
    ]
