# Generated by Django 5.2.7 on 2025-10-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_alter_sensitiveidentity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrole',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this a signed artist/internal role or external contractor?'),
        ),
    ]
