# Generated by Django 5.2.7 on 2025-10-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_entityrole_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for the entity', null=True, upload_to='entity_photos/'),
        ),
    ]
