# Generated by Django 5.2.7 on 2025-11-04 21:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('identity', '0016_entity_alias_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofilehistory',
            name='client_profile',
        ),
        migrations.RemoveField(
            model_name='clientprofilehistory',
            name='changed_by',
        ),
        migrations.CreateModel(
            name='DepartmentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this entity was added to the department')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete: hide entity from department without removing the record')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this entity to the department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_added', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='The department this entity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='active_entities', to='api.department')),
                ('entity', models.ForeignKey(help_text='The entity that belongs to this department', on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='identity.entity')),
            ],
            options={
                'verbose_name': 'Department Entity',
                'verbose_name_plural': 'Department Entities',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(blank=True, db_index=True, help_text='Overall client health score (1-10). Can be manually set or auto-calculated.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('collaboration_frequency_score', models.IntegerField(blank=True, help_text='Score based on how often we work with this client (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('feedback_score', models.IntegerField(blank=True, help_text='Score based on client feedback quality and responsiveness (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('payment_latency_score', models.IntegerField(blank=True, help_text='Score based on payment timeliness (1-10, 10=always on time)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text="Notes about this client's health score and reliability")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='The department this score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entity_scores', to='api.department')),
                ('entity', models.ForeignKey(help_text='The entity this score belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='identity.entity')),
                ('updated_by', models.ForeignKey(help_text='Last user who updated this score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_scores_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Score',
                'verbose_name_plural': 'Entity Scores',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(blank=True, help_text='Health score at this point in time', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('collaboration_frequency_score', models.IntegerField(blank=True, help_text='Collaboration frequency score at this point in time', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('feedback_score', models.IntegerField(blank=True, help_text='Feedback score at this point in time', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('payment_latency_score', models.IntegerField(blank=True, help_text='Payment latency score at this point in time', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Notes at this point in time')),
                ('change_reason', models.TextField(blank=True, help_text='Optional reason for this change')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_score_changes', to=settings.AUTH_USER_MODEL)),
                ('entity_score', models.ForeignKey(help_text='The entity score this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='identity.entityscore')),
            ],
            options={
                'verbose_name': 'Entity Score History',
                'verbose_name_plural': 'Entity Score Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='ClientProfileHistory',
        ),
        migrations.AddIndex(
            model_name='departmententity',
            index=models.Index(fields=['department', 'is_active'], name='identity_de_departm_0ecff2_idx'),
        ),
        migrations.AddIndex(
            model_name='departmententity',
            index=models.Index(fields=['entity', 'department'], name='identity_de_entity__f1f8bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmententity',
            unique_together={('entity', 'department')},
        ),
        migrations.AddIndex(
            model_name='entityscore',
            index=models.Index(fields=['entity', 'department'], name='identity_en_entity__59d140_idx'),
        ),
        migrations.AddIndex(
            model_name='entityscore',
            index=models.Index(fields=['department', 'health_score'], name='identity_en_departm_2360fb_idx'),
        ),
        migrations.AddIndex(
            model_name='entityscore',
            index=models.Index(fields=['health_score'], name='identity_en_health__93d061_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityscore',
            unique_together={('entity', 'department')},
        ),
        migrations.AddIndex(
            model_name='entityscorehistory',
            index=models.Index(fields=['entity_score', '-changed_at'], name='identity_en_entity__400a53_idx'),
        ),
        migrations.AddIndex(
            model_name='entityscorehistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='identity_en_changed_e8d9a4_idx'),
        ),
    ]
