# Generated by Django 5.2.7 on 2025-11-04 21:32

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_add_department_entity_and_rename_to_entity_score'),
    ]

    operations = [
        # Enable PostgreSQL trigram extension for fuzzy search
        TrigramExtension(),

        # Add GIN index on Entity.display_name for fast trigram similarity search
        migrations.AddIndex(
            model_name='entity',
            index=GinIndex(
                fields=['display_name'],
                name='entity_name_trgm_idx',
                opclasses=['gin_trgm_ops']
            ),
        ),
    ]
