# Generated by Django 5.2.7 on 2025-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_enable_pg_trgm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entity',
            name='entity_name_trgm_idx',
        ),
        migrations.AddField(
            model_name='entity',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address (separate from physical address)', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email address for billing/invoices', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='exclusivities_active',
            field=models.JSONField(blank=True, default=list, help_text="Active exclusivities for artist (e.g., [{brand: 'X', category: 'Beverage', until: '2025-12-31'}])"),
        ),
        migrations.AddField(
            model_name='entity',
            name='holding',
            field=models.CharField(blank=True, help_text='Parent company or holding group (e.g., WPP, Publicis)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='rate_tier',
            field=models.CharField(blank=True, choices=[('A', 'A-Tier'), ('B', 'B-Tier'), ('C', 'C-Tier')], help_text='Artist rate tier for image rights deals (A/B/C)', max_length=1, null=True),
        ),
    ]
