# Generated by Django 5.2.7 on 2025-10-12 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique contract identifier', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Contract title', max_length=255)),
                ('placeholder_values', models.JSONField(default=dict, help_text='Values used to fill placeholders')),
                ('gdrive_file_id', models.CharField(blank=True, help_text='Google Drive file ID of contract', max_length=255)),
                ('gdrive_file_url', models.URLField(blank=True, help_text='Google Drive file URL')),
                ('is_public', models.BooleanField(default=False, help_text='Whether contract is publicly accessible')),
                ('public_share_url', models.URLField(blank=True, help_text='Public sharing URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('dropbox_sign_request_id', models.CharField(blank=True, help_text='Dropbox Sign signature request ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_email', models.EmailField(help_text='Email of the signer', max_length=254)),
                ('signer_name', models.CharField(help_text='Name of the signer', max_length=255)),
                ('signer_role', models.CharField(blank=True, help_text="Role of the signer (e.g., 'Client', 'Contractor')", max_length=100)),
                ('dropbox_sign_signature_id', models.CharField(blank=True, help_text='Dropbox Sign signature ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('gdrive_template_file_id', models.CharField(help_text='Google Drive file ID of the template document', max_length=255)),
                ('placeholders', models.JSONField(default=list, help_text='Array of placeholder definitions')),
                ('gdrive_output_folder_id', models.CharField(help_text='Google Drive folder ID for generated contracts', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracttemplate'),
        ),
        migrations.CreateModel(
            name='ContractTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number')),
                ('gdrive_file_id', models.CharField(help_text='Google Drive file ID of this version', max_length=255)),
                ('placeholders_snapshot', models.JSONField(default=list)),
                ('change_description', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contracttemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracttemplateversion'),
        ),
    ]
