# Generated by Django 5.2.7 on 2025-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gdrive_pdf_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID of PDF version', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='gdrive_pdf_file_url',
            field=models.URLField(blank=True, help_text='Google Drive file URL (PDF)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID of contract (Google Docs)', max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='gdrive_file_url',
            field=models.URLField(blank=True, help_text='Google Drive file URL (Google Docs)'),
        ),
    ]
