# Generated by Django 5.2.7 on 2025-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_gdrive_pdf_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async contract generation', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if contract generation failed'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
