# Generated by Django 5.2.7 on 2025-10-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contracttemplate_series'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractshare',
            new_name='contracts_c_contrac_0f719b_idx',
            old_name='contracts_c_contrac_idx',
        ),
        migrations.RenameIndex(
            model_name='contractshare',
            new_name='contracts_c_share_t_cd86f3_idx',
            old_name='contracts_c_share_t_idx',
        ),
        migrations.RenameIndex(
            model_name='contractshare',
            new_name='contracts_c_valid_f_ec12ae_idx',
            old_name='contracts_c_valid_f_idx',
        ),
        migrations.AddField(
            model_name='contractterms',
            name='commission_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Range-based commission structure: first_years, middle_years, last_years with share type values'),
        ),
    ]
