# Generated by Django 5.2.7 on 2025-10-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_department_role_and_more'),
        ('contracts', '0010_webhookevent_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Owning department for access control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='api.department'),
        ),
        migrations.AlterField(
            model_name='contracttypepolicy',
            name='department',
            field=models.CharField(choices=[('digital', 'Digital'), ('sales', 'Sales'), ('publishing', 'Publishing')], db_index=True, max_length=50),
        ),
    ]
