# Generated by Django 5.2.7 on 2025-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='cui',
            field=models.CharField(blank=True, help_text='CUI - Cod Unic de Înregistrare (e.g., 12345678 or RO12345678)', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Trade Registry number (e.g., J40/12345/2020)', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT number (optional, if different from CUI)', max_length=100),
        ),
    ]
