# Generated by Django 5.2.7 on 2025-10-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companysettings_cui_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysettings',
            old_name='cui',
            new_name='cif',
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='cif',
            field=models.CharField(blank=True, help_text='C.I.F. - Cod de Identificare Fiscală (e.g., 12345678 or RO12345678)', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT number (optional, if different from C.I.F.)', max_length=100),
        ),
    ]
