# Generated by Django 5.2.7 on 2025-10-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_companysettings_cui_companysettings_cif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='admin_name',
            field=models.CharField(blank=True, help_text='Name of company administrator/representative (e.g., Maria Filip George)', max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='admin_role',
            field=models.CharField(blank=True, help_text='Role/title of administrator (e.g., Administrator, Director General)', max_length=100),
        ),
    ]
