# Generated by Django 5.2.7 on 2025-10-28 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companysettings_admin_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_department', models.CharField(choices=[('digital', 'Digital'), ('sales', 'Sales')], db_index=True, help_text='Requested department', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from user explaining the request')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/Manager who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_department_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Request',
                'verbose_name_plural': 'Department Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_departm_status_7a0a98_idx'), models.Index(fields=['user', 'status'], name='api_departm_user_id_234007_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('administrator', 'Administrator'), ('digital_manager', 'Digital Manager'), ('digital_employee', 'Digital Employee'), ('sales_manager', 'Sales Manager'), ('sales_employee', 'Sales Employee')], db_index=True, default='guest', help_text='User role for access control', max_length=50)),
                ('department', models.CharField(blank=True, choices=[(None, 'None'), ('digital', 'Digital'), ('sales', 'Sales')], db_index=True, help_text='Department: Digital or Sales', max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('setup_completed', models.BooleanField(default=False, help_text='Has user completed initial setup?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='api_userpro_role_9579a2_idx'), models.Index(fields=['department'], name='api_userpro_departm_4dcd85_idx')],
            },
        ),
    ]
