# Generated by Django 5.2.7 on 2025-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_departmentrequest_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('digital', 'Digital'), ('sales', 'Sales'), ('legal', 'Legal')], db_index=True, help_text='Department: Digital or Sales', max_length=50, null=True),
        ),
    ]
