# Generated by Django 5.2.7 on 2025-10-31 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_departments_roles_users'),
    ]

    operations = [
        # Step 1: Remove old CharField fields (now that data is migrated)
        migrations.RemoveField(
            model_name='userprofile',
            name='role_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department_old',
        ),
        # Step 2: Make role field non-nullable (all users must have a role)
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(
                help_text="User's role in the system",
                on_delete=django.db.models.deletion.PROTECT,
                related_name='users',
                to='api.role'
            ),
        ),
        # department remains nullable (administrators don't need departments)
    ]
