# Generated by Django 5.2.7 on 2025-10-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cleanup_old_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='api_userpro_role_id_4a16d0_idx',
            old_name='api_userpro_role_9579a2_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='api_userpro_departm_438aff_idx',
            old_name='api_userpro_departm_4dcd85_idx',
        ),
    ]
