# Generated by Django 5.2.7 on 2025-11-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='api_userpro_role_id_4a16d0_idx',
            old_name='api_userpro_role_9579a2_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='api_userpro_departm_438aff_idx',
            old_name='api_userpro_departm_4dcd85_idx',
        ),
    ]
