# Generated by Django 5.2.7 on 2025-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_admin_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentrequest',
            name='requested_department',
            field=models.CharField(choices=[('digital', 'Digital'), ('sales', 'Sales'), ('legal', 'Legal'), ('publishing', 'Publishing'), ('label', 'Label'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('special_operations', 'Special Operations')], db_index=True, help_text='Requested department', max_length=50),
        ),
    ]
