# Generated by Django 5.2.7 on 2025-11-04 01:32

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('catalog', '0001_initial'),
        ('contracts', '0011_alter_contract_department_and_more'),
        ('identity', '0016_entity_alias_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('artist', 'Artist'), ('label', 'Label'), ('aggregator', 'Aggregator')], db_index=True, help_text='Type of distribution deal (auto-populated from entity roles, but editable)', max_length=20)),
                ('global_revenue_share_percentage', models.DecimalField(decimal_places=2, help_text='Global revenue share percentage for the artist/entity (0.00-100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('signing_date', models.DateField(help_text='Date when the distribution deal was signed')),
                ('deal_status', models.CharField(choices=[('active', 'Active'), ('in_negotiation', 'In Negotiation'), ('expired', 'Expired')], db_index=True, default='in_negotiation', help_text='Current status of the distribution deal', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the distribution deal')),
                ('special_terms', models.TextField(blank=True, help_text='Special terms or conditions for this distribution deal')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(blank=True, help_text='Primary contact person for this distribution deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='identity.contactperson')),
                ('contract', models.ForeignKey(blank=True, help_text='Optional link to the contract for this distribution deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='contracts.contract')),
                ('created_by', models.ForeignKey(help_text='User who created this distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department this distribution belongs to (digital team)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='api.department')),
                ('entity', models.ForeignKey(help_text='The artist, label, or aggregator entity for this distribution deal', on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='identity.entity')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('tiktok', 'TikTok'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('amazon_music', 'Amazon Music'), ('soundcloud', 'SoundCloud'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('multi', 'Multi-Platform')], max_length=50), blank=True, default=list, help_text='Platforms where this item is distributed (Spotify, Apple Music, etc.)', size=None)),
                ('individual_revenue_share', models.DecimalField(blank=True, decimal_places=2, help_text='Override global revenue share for this specific item (optional)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('distribution_status', models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('taken_down', 'Taken Down')], db_index=True, default='pending', help_text='Distribution status for this catalog item', max_length=20)),
                ('release_date', models.DateField(blank=True, help_text='Release date for this catalog item', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to the distribution')),
                ('notes', models.TextField(blank=True, help_text="Additional notes about this catalog item's distribution")),
                ('distribution', models.ForeignKey(help_text='The distribution deal this catalog item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='distributions.distribution')),
                ('recording', models.ForeignKey(blank=True, help_text='Recording (single track) for this distribution', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='catalog.recording')),
                ('release', models.ForeignKey(blank=True, help_text='Release (album/EP) for this distribution', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='catalog.release')),
            ],
            options={
                'verbose_name': 'Distribution Catalog Item',
                'verbose_name_plural': 'Distribution Catalog Items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('tiktok', 'TikTok'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('amazon_music', 'Amazon Music'), ('soundcloud', 'SoundCloud'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('multi', 'Multi-Platform')], db_index=True, help_text='Platform this revenue report is for', max_length=50)),
                ('reporting_period', models.DateField(db_index=True, help_text='First day of the month for this reporting period (YYYY-MM-01)')),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue amount for this period', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency for the revenue amount', max_length=3)),
                ('streams', models.PositiveIntegerField(blank=True, help_text='Number of streams for this period (optional)', null=True)),
                ('downloads', models.PositiveIntegerField(blank=True, help_text='Number of downloads for this period (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this revenue report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(help_text='The catalog item this revenue report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='distributions.distributioncatalogitem')),
                ('created_by', models.ForeignKey(help_text='User who created this revenue report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distribution_revenue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribution Revenue Report',
                'verbose_name_plural': 'Distribution Revenue Reports',
                'ordering': ['-reporting_period', 'platform'],
            },
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['deal_status', 'department'], name='distributio_deal_st_a311c2_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['entity', 'deal_status'], name='distributio_entity__7ace2b_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['deal_type', 'deal_status'], name='distributio_deal_ty_9996e6_idx'),
        ),
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['signing_date'], name='distributio_signing_3639a6_idx'),
        ),
        migrations.AddIndex(
            model_name='distributioncatalogitem',
            index=models.Index(fields=['distribution', 'distribution_status'], name='distributio_distrib_ad4a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='distributioncatalogitem',
            index=models.Index(fields=['recording', 'distribution_status'], name='distributio_recordi_5409c3_idx'),
        ),
        migrations.AddIndex(
            model_name='distributioncatalogitem',
            index=models.Index(fields=['release', 'distribution_status'], name='distributio_release_b88d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributioncatalogitem',
            unique_together={('distribution', 'recording'), ('distribution', 'release')},
        ),
        migrations.AddIndex(
            model_name='distributionrevenuereport',
            index=models.Index(fields=['reporting_period', 'platform'], name='distributio_reporti_56061d_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionrevenuereport',
            index=models.Index(fields=['catalog_item', 'reporting_period'], name='distributio_catalog_17343a_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionrevenuereport',
            index=models.Index(fields=['platform', 'reporting_period'], name='distributio_platfor_1a5533_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributionrevenuereport',
            unique_together={('catalog_item', 'platform', 'reporting_period')},
        ),
    ]
