# Generated by Django 5.2.7 on 2025-01-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='deal_type',
            field=models.CharField(
                choices=[
                    ('artist', 'Artist'),
                    ('label', 'Label'),
                    ('aggregator', 'Aggregator'),
                    ('company', 'Company')
                ],
                db_index=True,
                help_text='Type of distribution deal (auto-populated from entity roles, but editable)',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='distribution',
            name='includes_dsps_youtube',
            field=models.BooleanField(
                default=False,
                help_text='Whether this distribution includes DSPs and/or YouTube'
            ),
        ),
    ]
