# Generated by Django 5.2.7 on 2025-11-10 16:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Tag name', max_length=100)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code for the tag', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this tag', on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Note title', max_length=255)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Rich text content in JSON format (Tiptap)')),
                ('content_text', models.TextField(blank=True, help_text='Plain text version of content for search')),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Whether this note is pinned to the top')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether this note is archived')),
                ('color', models.CharField(blank=True, help_text='Optional hex color code for the note', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the note was viewed or edited')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Owner of this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for this note', related_name='notes', to='notes.tag')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='notes_tag_user_id_86aeef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-is_pinned', '-updated_at'], name='notes_note_user_id_cea72d_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived'], name='notes_note_user_id_d0efd6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='notes_note_user_id_65a850_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='notes_note_search__2ae846_gin'),
        ),
    ]
