# Generated by Django 5.2.7 on 2025-10-31 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_client_profile_models'),
        ('campaigns', '0010_remove_client_health_score'),
        ('contracts', '0011_alter_contract_department_and_more'),
        ('crm_extensions', '0001_initial'),
        ('identity', '0015_add_client_profile_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this task', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='follow_up_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the follow-up reminder has been sent'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('client_requested', 'Client Requested'), ('internal', 'Internal'), ('recurring', 'Recurring'), ('blocked_external', 'Blocked by External')], db_index=True, help_text='Task tag for categorization', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use assigned_to_users instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tag', 'status'], name='crm_extensi_tag_0286fc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reminder_date', 'follow_up_reminder_sent'], name='crm_extensi_reminde_f7a5ce_idx'),
        ),
    ]
