# Generated by Django 5.2.7 on 2025-10-31 04:36

from django.db import migrations


def migrate_assigned_to_users(apps, schema_editor):
    """
    Migrate data from assigned_to (ForeignKey) to assigned_to_users (ManyToMany).
    For each task with an assigned_to value, add that user to assigned_to_users.
    """
    Task = apps.get_model('crm_extensions', 'Task')

    for task in Task.objects.filter(assigned_to__isnull=False):
        task.assigned_to_users.add(task.assigned_to)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: copy first assigned_to_users back to assigned_to.
    """
    Task = apps.get_model('crm_extensions', 'Task')

    for task in Task.objects.all():
        first_user = task.assigned_to_users.first()
        if first_user:
            task.assigned_to = first_user
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0002_task_assigned_to_users_task_follow_up_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_assigned_to_users, reverse_migration),
    ]
