# Generated by Django 5.2.7 on 2025-10-31 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0003_migrate_assigned_to_users'),
        ('identity', '0015_add_client_profile_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('edit', 'Edit Request'), ('delete', 'Delete Request')], db_index=True, help_text='Type of request (edit or delete)', max_length=20)),
                ('message', models.TextField(help_text='Explanation of what needs to be changed/deleted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the request', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin when approving/rejecting')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Entity this request is for', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='identity.entity')),
                ('requested_by', models.ForeignKey(help_text='User who requested the change', on_delete=django.db.models.deletion.CASCADE, related_name='entity_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entity_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Change Request',
                'verbose_name_plural': 'Entity Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='crm_extensi_status_ae2198_idx'), models.Index(fields=['requested_by', '-created_at'], name='crm_extensi_request_6e88ad_idx'), models.Index(fields=['entity', 'status'], name='crm_extensi_entity__10739a_idx')],
            },
        ),
    ]
