# Generated by Django 5.2.7 on 2025-11-03 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0004_entitychangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assignee', 'Assignee'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='assignee', help_text='Role of this user in the task', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crm_extensions.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ['role', 'assigned_at'],
                'indexes': [models.Index(fields=['task', 'role'], name='crm_extensi_task_id_c980bb_idx'), models.Index(fields=['user', 'role'], name='crm_extensi_user_id_f004c8_idx')],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
