# Generated by Django 5.2.7 on 2025-11-03 22:02

from django.db import migrations


def migrate_assigned_users_to_assignments(apps, schema_editor):
    """
    Migrate existing assigned_to_users M2M relationships to TaskAssignment model.

    For each task with assigned users, create TaskAssignment records with:
    - role='assignee' (default)
    - assigned_at=task.created_at (approximate)
    - assigned_by=task.created_by (best guess)
    """
    Task = apps.get_model('crm_extensions', 'Task')
    TaskAssignment = apps.get_model('crm_extensions', 'TaskAssignment')

    tasks_migrated = 0
    assignments_created = 0

    for task in Task.objects.all():
        # Get all users assigned via the old M2M field
        assigned_users = task.assigned_to_users.all()

        for user in assigned_users:
            # Create TaskAssignment record
            TaskAssignment.objects.create(
                task=task,
                user=user,
                role='assignee',  # Default role
                assigned_by=task.created_by if task.created_by else None
            )
            assignments_created += 1

        if assigned_users.exists():
            tasks_migrated += 1

    print(f"\nMigrated {tasks_migrated} tasks with {assignments_created} total assignments")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: copy TaskAssignment back to assigned_to_users M2M.
    """
    Task = apps.get_model('crm_extensions', 'Task')
    TaskAssignment = apps.get_model('crm_extensions', 'TaskAssignment')

    for task in Task.objects.all():
        # Get all assignments
        assignments = TaskAssignment.objects.filter(task=task)

        # Add users back to M2M field
        for assignment in assignments:
            task.assigned_to_users.add(assignment.user)


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0005_create_taskassignment_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_assigned_users_to_assignments,
            reverse_migration
        ),
    ]
