# Generated by Django 5.2.7 on 2025-11-03 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0006_migrate_assigned_users_to_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_users',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(help_text='Users assigned to this task', related_name='assigned_tasks', through='crm_extensions.TaskAssignment', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
