# Generated by Django 5.2.7 on 2025-11-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('artist_sales', '0002_alter_approval_file_url'),
        ('campaigns', '0016_rename_campaigns_c_campaig_1ae638_idx_campaigns_c_campaig_bc4d6f_idx_and_more'),
        ('catalog', '0003_add_song_artist_and_featured_artists'),
        ('contracts', '0011_alter_contract_department_and_more'),
        ('crm_extensions', '0007_replace_assigned_to_users_with_through'),
        ('identity', '0019_remove_entity_entity_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this trigger', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of when and why this trigger fires')),
                ('trigger_entity_type', models.CharField(db_index=True, help_text="Entity type that triggers this (e.g., 'work', 'contract')", max_length=50)),
                ('trigger_event', models.CharField(choices=[('created', 'Entity Created'), ('updated', 'Entity Updated'), ('status_changed', 'Status Changed')], db_index=True, help_text='Event type that triggers this', max_length=50)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='\n        Optional conditions that must be met for trigger to fire.\n        Example: {"field": "contract_type", "operator": "equals", "value": "publishing"}\n        ')),
                ('creates_task', models.BooleanField(default=True, help_text='Whether this trigger creates a task')),
                ('task_config', models.JSONField(default=dict, help_text='\n        Configuration for task creation.\n        Example: {\n            "title_template": "Handle contract for {work.name}",\n            "description_template": "New contract created for work {work.name}",\n            "department": "publishing",\n            "priority": 3,\n            "task_type": "contract_prep"\n        }\n        ')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this trigger is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flow Trigger',
                'verbose_name_plural': 'Flow Triggers',
                'ordering': ['trigger_entity_type', 'trigger_event'],
            },
        ),
        migrations.CreateModel(
            name='ManualTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this trigger', max_length=200)),
                ('button_label', models.CharField(help_text="Label shown on the button (e.g., 'Send to Marketing')", max_length=100)),
                ('button_style', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='primary', help_text='Visual style of the button', max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text="Entity type this button appears on (e.g., 'opportunity', 'contract')", max_length=50)),
                ('context', models.CharField(blank=True, help_text="Specific context where button appears (e.g., 'deliverable_list', 'detail_page')", max_length=100)),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('start_flow', 'Start Flow'), ('update_status', 'Update Status')], default='create_task', help_text='Action performed when button is clicked', max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text='\n        Configuration for the action.\n        Example: {\n            "task_title_template": "Create {deliverable_type} for {opportunity.name}",\n            "target_department": "marketing",\n            "flow": "marketing_deliverable",\n            "priority": 2\n        }\n        ')),
                ('required_permissions', models.JSONField(blank=True, default=list, help_text='List of required permissions to use this trigger')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this trigger is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Trigger',
                'verbose_name_plural': 'Manual Triggers',
                'ordering': ['entity_type', 'context', 'button_label'],
            },
        ),
        migrations.CreateModel(
            name='StageAdvancementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this rule', max_length=200)),
                ('entity_type', models.CharField(db_index=True, help_text="Entity type this rule applies to (e.g., 'song', 'opportunity', 'contract')", max_length=50)),
                ('from_stage', models.CharField(db_index=True, help_text="Stage to advance from (e.g., 'publishing', 'negotiation')", max_length=100)),
                ('to_stage', models.CharField(help_text="Stage to advance to (e.g., 'label', 'won')", max_length=100)),
                ('criteria', models.JSONField(help_text='\n        ALL criteria must be met for stage advancement.\n        Example: [\n            {"entity": "contract", "field": "status", "operator": "equals", "value": "signed"},\n            {"entity": "work", "field": "iswc", "operator": "is_not_null"},\n            {"checklist_stage": "publishing", "all_items_complete": true}\n        ]\n        ')),
                ('priority', models.IntegerField(default=0, help_text='Rule priority (higher = evaluated first)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stage Advancement Rule',
                'verbose_name_plural': 'Stage Advancement Rules',
                'ordering': ['entity_type', 'from_stage', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='flow_step_history',
            field=models.JSONField(blank=True, default=list, help_text='\n        History of completed flow steps.\n        Example: [\n            {"step_name": "generate_document", "step_display": "Generate Document",\n             "completed_at": "2025-01-15T10:30:00Z", "completed_by": 42}\n        ]\n        '),
        ),
        migrations.AddField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, help_text='Opportunity this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to='artist_sales.opportunity'),
        ),
        migrations.AddField(
            model_name='task',
            name='recording',
            field=models.ForeignKey(blank=True, help_text='Recording this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalog.recording'),
        ),
        migrations.AddField(
            model_name='task',
            name='song',
            field=models.ForeignKey(blank=True, help_text='Song this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalog.song'),
        ),
        migrations.AddField(
            model_name='task',
            name='song_checklist_item',
            field=models.ForeignKey(blank=True, help_text='Song checklist item this task represents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='catalog.songchecklistitem'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_checklist_name',
            field=models.CharField(blank=True, help_text='Original checklist item name (for reference)', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='source_stage',
            field=models.CharField(blank=True, help_text='Stage this task belongs to (for display when stage changes)', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(blank=True, help_text='Work this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalog.work'),
        ),
        migrations.CreateModel(
            name='FlowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the flow (e.g., 'Contract Signing Process')", max_length=200, unique=True)),
                ('entity_type', models.CharField(db_index=True, help_text="Entity type this flow applies to (e.g., 'contract', 'recording', 'deliverable')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this flow')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this flow is currently active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Primary department that owns this flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='api.department')),
            ],
            options={
                'verbose_name': 'Flow Definition',
                'verbose_name_plural': 'Flow Definitions',
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='Flow this task follows (if multi-step)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_extensions.flowdefinition'),
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal step identifier (e.g., 'generate_document')", max_length=100)),
                ('display_name', models.CharField(help_text="User-facing step name (e.g., 'Generate contract document')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this step involves')),
                ('order', models.IntegerField(help_text='Sequence order of this step in the flow (1, 2, 3...)')),
                ('auto_complete_criteria', models.JSONField(help_text='\n        Criteria that automatically completes this step when met.\n        Example: {"entity": "contract", "field": "status", "operator": "equals", "value": "signed"}\n        Operators: equals, is_not_null, in, greater_than, less_than\n        ')),
                ('actions', models.JSONField(blank=True, default=list, help_text='\n        Actions to execute when this step is reached/completed.\n        Example: [\n            {"type": "update_entity", "entity": "contract", "field": "status", "value": "draft"},\n            {"type": "complete_checklist", "song_checklist_item_name": "Contract signed"},\n            {"type": "emit_event", "event_name": "contract.draft_ready"},\n            {"type": "send_notification", "to": "assigned_users", "message": "Contract draft ready"}\n        ]\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(help_text='Flow this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm_extensions.flowdefinition')),
            ],
            options={
                'verbose_name': 'Flow Step',
                'verbose_name_plural': 'Flow Steps',
                'ordering': ['flow', 'order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='current_flow_step',
            field=models.ForeignKey(blank=True, help_text='Current step in the flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tasks', to='crm_extensions.flowstep'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['song', 'status'], name='crm_extensi_song_id_1d05a9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['work', 'status'], name='crm_extensi_work_id_40a779_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['recording', 'status'], name='crm_extensi_recordi_bc7b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['opportunity', 'status'], name='crm_extensi_opportu_ffaef9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['flow', 'current_flow_step'], name='crm_extensi_flow_id_a1f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['song_checklist_item'], name='crm_extensi_song_ch_7308c9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_stage', 'status'], name='crm_extensi_source__a57771_idx'),
        ),
        migrations.AddField(
            model_name='flowtrigger',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='Flow to attach to created tasks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='crm_extensions.flowdefinition'),
        ),
        migrations.AddField(
            model_name='manualtrigger',
            name='visible_to_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments that can see and use this trigger', related_name='manual_triggers', to='api.department'),
        ),
        migrations.AddIndex(
            model_name='stageadvancementrule',
            index=models.Index(fields=['entity_type', 'from_stage', 'is_active'], name='crm_extensi_entity__892255_idx'),
        ),
        migrations.AddIndex(
            model_name='flowstep',
            index=models.Index(fields=['flow', 'order'], name='crm_extensi_flow_id_f50a94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together={('flow', 'order')},
        ),
        migrations.AddIndex(
            model_name='flowtrigger',
            index=models.Index(fields=['trigger_entity_type', 'trigger_event', 'is_active'], name='crm_extensi_trigger_5f1765_idx'),
        ),
        migrations.AddIndex(
            model_name='manualtrigger',
            index=models.Index(fields=['entity_type', 'context', 'is_active'], name='crm_extensi_entity__161389_idx'),
        ),
    ]
