# Generated by Django 5.2.7 on 2025-11-09 19:37

from django.db import migrations


def populate_flow_triggers(apps, schema_editor):
    """Create automatic flow triggers for contract tasks and release tasks."""
    FlowTrigger = apps.get_model('crm_extensions', 'FlowTrigger')

    # 1. Work created → Contract task for Publishing Manager
    FlowTrigger.objects.get_or_create(
        name='Auto-create contract task for Work',
        defaults={
            'description': 'Automatically creates a contract task for Publishing Manager when Work is created',
            'trigger_entity_type': 'work',
            'trigger_event': 'created',
            'trigger_conditions': {},
            'creates_task': True,
            'task_config': {
                'title_template': 'Generate the contract for Work "{work.title}"',
                'description_template': 'Create and manage the publishing contract for this work.',
                'department': 'publishing',
                'priority': 3,
                'task_type': 'contract_prep',
            },
            'flow': None,
            'is_active': True,
        }
    )

    # 2. Recording created → Contract task for Label Manager
    FlowTrigger.objects.get_or_create(
        name='Auto-create contract task for Recording',
        defaults={
            'description': 'Automatically creates a contract task for Label Manager when Recording is created',
            'trigger_entity_type': 'recording',
            'trigger_event': 'created',
            'trigger_conditions': {},
            'creates_task': True,
            'task_config': {
                'title_template': 'Generate the contract for Recording "{recording.title}"',
                'description_template': 'Create and manage the production contract for this recording.',
                'department': 'label',
                'priority': 3,
                'task_type': 'contract_prep',
            },
            'flow': None,
            'is_active': True,
        }
    )


def populate_manual_triggers(apps, schema_editor):
    """Create manual triggers for marketing requests and deliverables."""
    ManualTrigger = apps.get_model('crm_extensions', 'ManualTrigger')
    Department = apps.get_model('api', 'Department')

    # Get departments
    try:
        label_dept = Department.objects.get(name='label')
        sales_dept = Department.objects.get(name='sales')
    except Department.DoesNotExist:
        # If departments don't exist yet, skip this
        return

    # 1. Request Marketing button (for songs in label_recording stage)
    trigger, created = ManualTrigger.objects.get_or_create(
        name='Request Marketing for Song',
        defaults={
            'button_label': 'Request Marketing',
            'button_style': 'primary',
            'entity_type': 'song',
            'context': 'label_recording_stage',
            'action_type': 'create_task',
            'action_config': {
                'task_title_template': 'Create marketing assets for Song "{song.name}"',
                'description': 'Create all required marketing assets for this song',
                'target_department': 'marketing',
                'priority': 3,
                'task_type': 'content_creation',
            },
            'required_permissions': [],
            'is_active': True,
        }
    )
    if created:
        trigger.visible_to_departments.add(label_dept)

    # 2. Send to Marketing button (for opportunity deliverables)
    trigger, created = ManualTrigger.objects.get_or_create(
        name='Send Deliverable to Marketing',
        defaults={
            'button_label': 'Send to Marketing',
            'button_style': 'primary',
            'entity_type': 'opportunity',
            'context': 'deliverable_item',
            'action_type': 'create_task',
            'action_config': {
                'task_title_template': 'Create {deliverable_type} for Opportunity "{opportunity.name}"',
                'description': 'Create the requested deliverable for this opportunity',
                'target_department': 'marketing',
                'priority': 2,
                'task_type': 'content_creation',
            },
            'required_permissions': [],
            'is_active': True,
        }
    )
    if created:
        trigger.visible_to_departments.add(sales_dept)


def reverse_triggers(apps, schema_editor):
    """Remove the triggers created by this migration."""
    FlowTrigger = apps.get_model('crm_extensions', 'FlowTrigger')
    ManualTrigger = apps.get_model('crm_extensions', 'ManualTrigger')

    FlowTrigger.objects.filter(
        name__in=[
            'Auto-create contract task for Work',
            'Auto-create contract task for Recording',
        ]
    ).delete()

    ManualTrigger.objects.filter(
        name__in=[
            'Request Marketing for Song',
            'Send Deliverable to Marketing',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0008_flowtrigger_manualtrigger_stageadvancementrule_and_more'),
        ('api', '__latest__'),  # Need Department model
    ]

    operations = [
        migrations.RunPython(populate_flow_triggers, reverse_triggers),
        migrations.RunPython(populate_manual_triggers, reverse_triggers),
    ]
