# Generated by Django 5.2.7 on 2025-11-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_sales', '0002_alter_approval_file_url'),
        ('crm_extensions', '0009_populate_flow_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deliverable',
            field=models.ForeignKey(blank=True, help_text='Deliverable this task is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='artist_sales.opportunitydeliverable'),
        ),
    ]
