# Generated by Django 5.2.7 on 2025-11-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0011_update_deliverable_trigger'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='crm_extensi_flow_id_a1f33f_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='current_flow_step',
        ),
        migrations.RemoveField(
            model_name='task',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='task',
            name='flow_step_history',
        ),
    ]
