# Generated by Django 5.2.7 on 2025-11-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0012_remove_flow_fields'),
    ]

    operations = [
        # Remove unique_together before removing fields
        migrations.AlterUniqueTogether(
            name='flowstep',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flowdefinition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='flowtrigger',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='flowstep',
            name='flow',
        ),
        migrations.DeleteModel(
            name='StageAdvancementRule',
        ),
        migrations.DeleteModel(
            name='FlowDefinition',
        ),
        migrations.DeleteModel(
            name='FlowStep',
        ),
    ]
