# Generated by Django 5.2.7 on 2025-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_extensions', '0013_remove_unused_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deliverable', 'status'], name='crm_extensi_deliver_idx'),
        ),
    ]
