# Generated by Django 5.2.7 on 2025-11-06 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_departmentrequest_requested_department'),
        ('catalog', '0001_initial'),
        ('identity', '0019_remove_entity_entity_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Song title', max_length=255)),
                ('genre', models.CharField(blank=True, help_text='Primary genre', max_length=100)),
                ('language', models.CharField(default='en', help_text='Primary language code', max_length=50)),
                ('duration', models.DurationField(blank=True, help_text='Song duration (computed from recording)', null=True)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('label_recording', 'Label - Recording'), ('marketing_assets', 'Marketing - Assets'), ('label_review', 'Label - Review'), ('ready_for_digital', 'Ready for Digital'), ('digital_distribution', 'Digital Distribution'), ('released', 'Released'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Current workflow stage', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Song priority level', max_length=20)),
                ('target_release_date', models.DateField(blank=True, db_index=True, help_text='Target release date for this song', null=True)),
                ('stage_deadline', models.DateField(blank=True, db_index=True, help_text='Deadline for completing current stage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_entered_at', models.DateTimeField(blank=True, help_text='When the song entered the current stage', null=True)),
                ('checklist_progress', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of checklist items complete (0-100)', max_digits=5)),
                ('is_overdue', models.BooleanField(db_index=True, default=False, help_text='Whether the song is past its stage deadline')),
                ('days_in_current_stage', models.IntegerField(default=0, help_text='Number of days in current stage')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether the song has been archived')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, help_text='Whether the song is manually flagged as blocked')),
                ('blocked_reason', models.TextField(blank=True, help_text='Reason why the song is blocked')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible to all departments')),
                ('external_notes', models.TextField(blank=True, help_text='Notes for external partners')),
                ('artist', models.ForeignKey(blank=True, help_text='Primary artist entity (can be TBD initially)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='identity.entity')),
                ('assigned_department', models.ForeignKey(blank=True, help_text='Department currently responsible for this song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_songs', to='api.department')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Specific user assigned to work on this song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_songs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this song', on_delete=django.db.models.deletion.PROTECT, related_name='songs_created', to=settings.AUTH_USER_MODEL)),
                ('recordings', models.ManyToManyField(blank=True, help_text='Associated recordings', related_name='songs', to='catalog.recording')),
                ('releases', models.ManyToManyField(blank=True, help_text='Associated releases', related_name='songs', to='catalog.release')),
                ('stage_updated_by', models.ForeignKey(blank=True, help_text='Last user to update the stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_stage_updates', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, help_text='Associated musical work (composition)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='catalog.work')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('stage_transition', 'Stage Transition'), ('assignment', 'Assigned to You'), ('deadline_approaching', 'Deadline Approaching'), ('overdue', 'Overdue'), ('asset_submitted', 'Assets Submitted'), ('asset_approved', 'Assets Approved'), ('asset_rejected', 'Assets Rejected'), ('ready_for_review', 'Ready for Review'), ('sent_to_digital', 'Sent to Digital'), ('checklist_incomplete', 'Checklist Item Incomplete'), ('blocking_issue', 'Blocking Issue')], db_index=True, help_text='Type of alert', max_length=50)),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('message', models.TextField(help_text='Alert message')),
                ('action_url', models.CharField(blank=True, help_text='Link to song detail page', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text="Action button label (e.g., 'Review Now')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the alert was created')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the alert has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the alert was read', null=True)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('important', 'Important'), ('urgent', 'Urgent')], db_index=True, default='info', help_text='Alert priority level', max_length=20)),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='catalog.song')),
                ('target_department', models.ForeignKey(blank=True, help_text='Target department (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_alerts', to='api.department')),
                ('target_user', models.ForeignKey(blank=True, help_text='Target user (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song Alert',
                'verbose_name_plural': 'Song Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('cover_art', 'Cover Artwork'), ('back_cover', 'Back Cover'), ('press_photo', 'Press Photo'), ('promo_graphic', 'Promotional Graphic'), ('social_media', 'Social Media Asset'), ('lyric_video', 'Lyric Video'), ('visualizer', 'Visualizer'), ('other', 'Other')], db_index=True, help_text='Type of asset', max_length=50)),
                ('google_drive_url', models.URLField(help_text='Google Drive URL to the asset file')),
                ('file_format', models.CharField(blank=True, help_text='File format (jpg, png, mp4, etc.)', max_length=20)),
                ('width', models.IntegerField(blank=True, help_text='Width in pixels (for images)', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in pixels (for images)', null=True)),
                ('title', models.CharField(blank=True, help_text='Asset title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Asset description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the asset was uploaded')),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Needs Revision')], db_index=True, default='pending', help_text='Review status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the asset was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Review feedback or notes')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary asset for this type (e.g., primary cover art)')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_song_assets', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalog.song')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this asset', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_song_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song Asset',
                'verbose_name_plural': 'Song Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SongChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('label_recording', 'Label - Recording'), ('marketing_assets', 'Marketing - Assets'), ('label_review', 'Label - Review'), ('ready_for_digital', 'Ready for Digital'), ('digital_distribution', 'Digital Distribution'), ('released', 'Released'), ('archived', 'Archived')], db_index=True, help_text='Workflow stage this item belongs to', max_length=50)),
                ('category', models.CharField(help_text="Category (e.g., 'Legal', 'Audio', 'Metadata')", max_length=100)),
                ('item_name', models.CharField(help_text='Name of the checklist item', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the requirement')),
                ('order', models.IntegerField(default=0, help_text='Display order within stage')),
                ('required', models.BooleanField(default=True, help_text='Must complete to transition to next stage')),
                ('validation_type', models.CharField(choices=[('manual', 'Manual Check'), ('auto_field_exists', 'Auto - Field Exists'), ('auto_file_exists', 'Auto - File Uploaded'), ('auto_split_validated', 'Auto - Splits = 100%'), ('auto_entity_exists', 'Auto - Entity Created'), ('auto_count_minimum', 'Auto - Minimum Count'), ('auto_custom', 'Auto - Custom Function')], default='manual', help_text='How to validate this item', max_length=50)),
                ('validation_rule', models.JSONField(blank=True, help_text='Configuration for auto validators (JSON)', null=True)),
                ('is_complete', models.BooleanField(db_index=True, default=False, help_text='Whether this item is complete')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this item was completed', null=True)),
                ('help_text', models.TextField(blank=True, help_text='Instructions on how to complete this item')),
                ('help_link', models.URLField(blank=True, help_text='Link to documentation or tutorial')),
                ('is_blocker', models.BooleanField(default=False, help_text='Blocks stage transition if incomplete')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to complete this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, help_text='This item depends on another item being complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_items', to='catalog.songchecklistitem')),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Song Checklist Item',
                'verbose_name_plural': 'Song Checklist Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SongNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the note was created')),
                ('note_type', models.CharField(choices=[('comment', 'Comment'), ('status_update', 'Status Update'), ('sales_pitch', 'Sales Pitch'), ('feedback', 'Feedback'), ('system', 'System Note')], db_index=True, default='comment', help_text='Type of note', max_length=50)),
                ('content', models.TextField(help_text='Note content')),
                ('pitched_to_artist', models.CharField(blank=True, help_text='Artist the work was pitched to', max_length=255)),
                ('pitch_outcome', models.CharField(blank=True, choices=[('interested', 'Interested'), ('passed', 'Passed'), ('pending', 'Pending'), ('deal_made', 'Deal Made')], help_text='Outcome of the sales pitch', max_length=50)),
                ('is_internal', models.BooleanField(default=True, help_text='Internal vs external note')),
                ('author', models.ForeignKey(help_text='Author of the note', on_delete=django.db.models.deletion.PROTECT, related_name='song_notes', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalog.song')),
                ('visible_to_departments', models.ManyToManyField(blank=True, help_text='Departments that can see this note (empty = all)', related_name='visible_song_notes', to='api.department')),
            ],
            options={
                'verbose_name': 'Song Note',
                'verbose_name_plural': 'Song Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('label_recording', 'Label - Recording'), ('marketing_assets', 'Marketing - Assets'), ('label_review', 'Label - Review'), ('ready_for_digital', 'Ready for Digital'), ('digital_distribution', 'Digital Distribution'), ('released', 'Released'), ('archived', 'Archived')], help_text='Previous stage', max_length=50)),
                ('to_stage', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('label_recording', 'Label - Recording'), ('marketing_assets', 'Marketing - Assets'), ('label_review', 'Label - Review'), ('ready_for_digital', 'Ready for Digital'), ('digital_distribution', 'Digital Distribution'), ('released', 'Released'), ('archived', 'Archived')], help_text='New stage', max_length=50)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True, help_text='When the transition occurred')),
                ('transition_type', models.CharField(choices=[('forward', 'Forward Progress'), ('backward', 'Sent Back'), ('skip', 'Skipped Stage'), ('forced', 'Admin Override')], default='forward', help_text='Type of transition', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about why transition happened')),
                ('checklist_completion_at_transition', models.DecimalField(decimal_places=2, help_text='Checklist completion percentage at time of transition', max_digits=5)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('rejection_category', models.CharField(blank=True, help_text="Category of rejection (e.g., 'Audio Quality', 'Legal Issue')", max_length=100)),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='catalog.song')),
                ('transitioned_by', models.ForeignKey(help_text='User who performed the transition', on_delete=django.db.models.deletion.PROTECT, related_name='song_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Song Stage Transition',
                'verbose_name_plural': 'Song Stage Transitions',
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['stage', 'assigned_department'], name='catalog_son_stage_33cd43_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['target_release_date'], name='catalog_son_target__4038af_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_archived', 'stage'], name='catalog_son_is_arch_1b129d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['priority', 'stage'], name='catalog_son_priorit_88b560_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_by'], name='catalog_son_created_3c1438_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_overdue'], name='catalog_son_is_over_5f31b3_idx'),
        ),
        migrations.AddIndex(
            model_name='songalert',
            index=models.Index(fields=['target_department', 'is_read'], name='catalog_son_target__12db91_idx'),
        ),
        migrations.AddIndex(
            model_name='songalert',
            index=models.Index(fields=['target_user', 'is_read'], name='catalog_son_target__3d5786_idx'),
        ),
        migrations.AddIndex(
            model_name='songalert',
            index=models.Index(fields=['alert_type', 'created_at'], name='catalog_son_alert_t_521e42_idx'),
        ),
        migrations.AddIndex(
            model_name='songasset',
            index=models.Index(fields=['song', 'asset_type'], name='catalog_son_song_id_980267_idx'),
        ),
        migrations.AddIndex(
            model_name='songasset',
            index=models.Index(fields=['review_status'], name='catalog_son_review__f47b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='songchecklistitem',
            index=models.Index(fields=['song', 'stage', 'required'], name='catalog_son_song_id_e10eec_idx'),
        ),
        migrations.AddIndex(
            model_name='songchecklistitem',
            index=models.Index(fields=['is_complete'], name='catalog_son_is_comp_c751f8_idx'),
        ),
        migrations.AddIndex(
            model_name='songnote',
            index=models.Index(fields=['song', 'created_at'], name='catalog_son_song_id_daf0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='songnote',
            index=models.Index(fields=['note_type'], name='catalog_son_note_ty_c0eb05_idx'),
        ),
        migrations.AddIndex(
            model_name='songstagetransition',
            index=models.Index(fields=['song', 'transitioned_at'], name='catalog_son_song_id_7099ec_idx'),
        ),
        migrations.AddIndex(
            model_name='songstagetransition',
            index=models.Index(fields=['transition_type'], name='catalog_son_transit_bd51de_idx'),
        ),
    ]
