# Generated by Django 5.2.7 on 2025-11-06 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_song_songalert_songasset_songchecklistitem_songnote_and_more'),
        ('identity', '0019_remove_entity_entity_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue', 'Overdue Songs'), ('deadline_approaching', 'Deadline Approaching'), ('release_approaching', 'Release Approaching'), ('checklist_incomplete', 'Checklist Incomplete')], help_text='Type of alert to configure', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable this alert type')),
                ('days_threshold', models.IntegerField(blank=True, help_text="Number of days threshold (e.g., 2 for 'deadline in 2 days', 7 for 'release in 7 days')", null=True)),
                ('schedule_description', models.CharField(blank=True, help_text="Human-readable schedule description (e.g., 'Daily at midnight')", max_length=255)),
                ('notify_assigned_user', models.BooleanField(default=True, help_text='Send alert to the assigned user')),
                ('notify_department_managers', models.BooleanField(default=True, help_text='Send alert to department managers')),
                ('notify_song_creator', models.BooleanField(default=False, help_text='Send alert to song creator')),
                ('priority', models.CharField(choices=[('info', 'Info'), ('important', 'Important'), ('urgent', 'Urgent')], default='important', help_text='Alert priority level', max_length=20)),
                ('title_template', models.CharField(help_text='Alert title template (supports {song_title}, {days}, {deadline}, etc.)', max_length=255)),
                ('message_template', models.TextField(help_text='Alert message template (supports same variables as title)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who updated this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configurations',
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('featured', 'Featured Artist'), ('remixer', 'Remixer'), ('producer', 'Producer'), ('composer', 'Composer'), ('featuring', 'Featuring')], default='featured', help_text='Artist role on this song', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for featured artist billing (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(help_text='Artist entity', on_delete=django.db.models.deletion.CASCADE, related_name='song_credits', to='identity.entity')),
                ('song', models.ForeignKey(help_text='Song this artist credit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='artist_credits', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Song Artist',
                'verbose_name_plural': 'Song Artists',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, help_text='Featured artists with roles', related_name='featured_songs', through='catalog.SongArtist', to='identity.entity'),
        ),
        migrations.AddIndex(
            model_name='songartist',
            index=models.Index(fields=['song', 'order'], name='catalog_son_song_id_bde749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='songartist',
            unique_together={('song', 'artist', 'role')},
        ),
    ]
