# Generated by Django 5.2.7 on 2025-11-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_song_artist_and_featured_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='songchecklistitem',
            name='recording',
            field=models.ForeignKey(blank=True, help_text='Associated recording (if this is a recording-specific checklist item)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='catalog.recording'),
        ),
    ]
