# Generated by Django 5.2.7 on 2025-11-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_recording_to_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongStageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('publishing', 'Publishing'), ('label_recording', 'Label - Recording'), ('marketing_assets', 'Marketing - Assets'), ('label_review', 'Label - Review'), ('ready_for_digital', 'Ready for Digital'), ('digital_distribution', 'Digital Distribution'), ('released', 'Released'), ('archived', 'Archived')], help_text='Workflow stage', max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], db_index=True, default='not_started', help_text='Current status of this stage', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When work on this stage began', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this stage was completed', null=True)),
                ('blocked_reason', models.TextField(blank=True, help_text='Why this stage is blocked (if status=blocked)')),
                ('notes', models.TextField(blank=True, help_text='Notes about work in this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(help_text='Associated song', on_delete=django.db.models.deletion.CASCADE, related_name='stage_statuses', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Song Stage Status',
                'verbose_name_plural': 'Song Stage Statuses',
                'ordering': ['song', 'stage'],
                'indexes': [models.Index(fields=['song', 'status'], name='catalog_son_song_id_93ab28_idx'), models.Index(fields=['status'], name='catalog_son_status_ecacaf_idx')],
                'unique_together': {('song', 'stage')},
            },
        ),
    ]
