# Generated by Django 5.2.7 on 2025-11-12 15:54

from django.db import migrations
from django.utils import timezone


STAGES_ORDER = [
    'draft',
    'publishing',
    'label_recording',
    'marketing_assets',
    'label_review',
    'ready_for_digital',
    'digital_distribution',
    'released',
]


def populate_stage_statuses(apps, schema_editor):
    """
    Create SongStageStatus records for all existing songs.

    Logic:
    - Stages before current_stage: status='completed'
    - Current stage: status='in_progress', started_at=stage_entered_at
    - Stages after current_stage: status='not_started'
    """
    Song = apps.get_model('catalog', 'Song')
    SongStageStatus = apps.get_model('catalog', 'SongStageStatus')

    songs = Song.objects.all()
    stage_statuses_to_create = []

    for song in songs:
        current_stage = song.stage or 'draft'

        try:
            current_stage_idx = STAGES_ORDER.index(current_stage)
        except ValueError:
            # Handle archived or unknown stages - treat as draft
            current_stage_idx = 0

        for idx, stage_key in enumerate(STAGES_ORDER):
            if idx < current_stage_idx:
                # Completed stages
                status = 'completed'
                started_at = None
                completed_at = None
            elif idx == current_stage_idx:
                # Current active stage
                status = 'in_progress'
                started_at = song.stage_entered_at or song.created_at
                completed_at = None
            else:
                # Not started stages
                status = 'not_started'
                started_at = None
                completed_at = None

            stage_statuses_to_create.append(
                SongStageStatus(
                    song=song,
                    stage=stage_key,
                    status=status,
                    started_at=started_at,
                    completed_at=completed_at,
                )
            )

    # Bulk create for performance
    if stage_statuses_to_create:
        SongStageStatus.objects.bulk_create(stage_statuses_to_create, batch_size=500)
        print(f"Created {len(stage_statuses_to_create)} stage status records for {songs.count()} songs")


def reverse_populate(apps, schema_editor):
    """Remove all stage statuses"""
    SongStageStatus = apps.get_model('catalog', 'SongStageStatus')
    SongStageStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_songstagestatus'),
    ]

    operations = [
        migrations.RunPython(populate_stage_statuses, reverse_populate),
    ]
