# Generated by Django 5.2.7 on 2025-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_populate_song_stage_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='songchecklistitem',
            name='asset_url',
            field=models.URLField(blank=True, help_text='URL to the completed asset (e.g., Google Drive link, Dropbox link)', max_length=500),
        ),
    ]
