# Generated by Django 5.2.7 on 2025-11-05 19:39

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0012_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('identity', '0019_remove_entity_entity_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverablePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Pack name (e.g., 'Standard IG Package', 'TVC + Digital Bundle')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of what's included")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this pack is active/available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deliverable Pack',
                'verbose_name_plural': 'Deliverable Packs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsageTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the usage terms (e.g., 'Digital Only - 12mo', 'Global ATL + BTL - 24mo')", max_length=255)),
                ('usage_scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('digital', 'Digital'), ('atl', 'ATL (Above The Line)'), ('btl', 'BTL (Below The Line)'), ('ooh', 'OOH (Out of Home)'), ('packaging', 'Product Packaging'), ('in_store', 'In-Store'), ('global', 'Global Rights'), ('print', 'Print Media'), ('broadcast', 'Broadcast (TV/Radio)'), ('cinema', 'Cinema'), ('events', 'Events')], max_length=50), blank=True, default=list, help_text='Types of usage rights granted', size=None)),
                ('territories', models.JSONField(blank=True, default=list, help_text='List of ISO country codes for territories')),
                ('exclusivity_category', models.CharField(blank=True, help_text="Product category for exclusivity (e.g., 'Beverage', 'Automotive')", max_length=100)),
                ('exclusivity_duration_days', models.IntegerField(blank=True, help_text='Exclusivity duration in days', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_duration_days', models.IntegerField(default=365, help_text='Usage rights duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('extensions_allowed', models.BooleanField(default=False, help_text='Whether usage can be extended')),
                ('buyout', models.BooleanField(default=False, help_text='Whether this is a full buyout (perpetual rights)')),
                ('brand_list_blocked', models.JSONField(blank=True, default=list, help_text='List of competing brands blocked during exclusivity')),
                ('is_template', models.BooleanField(db_index=True, default=True, help_text='Whether this is a reusable template')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usage Terms',
                'verbose_name_plural': 'Usage Terms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(db_index=True, help_text='Title of the campaign', max_length=255)),
                ('brand_category', models.CharField(blank=True, help_text='Product/brand category (e.g., Beverage, Fashion, Tech)', max_length=100)),
                ('objectives', models.TextField(blank=True, help_text='Campaign objectives and goals')),
                ('target_audience', models.TextField(blank=True, help_text='Target audience description')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Marketing channels (Paid/Owned/ATL/BTL/OOH/Packaging, etc.)')),
                ('timing_start', models.DateField(blank=True, help_text='Desired campaign start date', null=True)),
                ('timing_end', models.DateField(blank=True, help_text='Desired campaign end date', null=True)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget range', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget range', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency for budget', max_length=3)),
                ('must_haves', models.TextField(blank=True, help_text='Must-have requirements')),
                ('nice_to_have', models.TextField(blank=True, help_text='Nice-to-have features')),
                ('brief_status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('pitched', 'Pitched'), ('lost', 'Lost'), ('won', 'Won')], db_index=True, default='new', help_text='Current status of the brief', max_length=20)),
                ('received_date', models.DateField(auto_now_add=True, help_text='Date when brief was received')),
                ('sla_due_date', models.DateField(blank=True, help_text='SLA response deadline', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Brand or agency requesting the brief', on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='identity.entity')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Primary contact person at the account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='identity.contactperson')),
                ('created_by', models.ForeignKey(help_text='User who created this brief', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department this brief belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='briefs', to='api.department')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated contract number', max_length=50, unique=True)),
                ('po_number', models.CharField(blank=True, help_text='Purchase Order number from client', max_length=100)),
                ('deal_title', models.CharField(db_index=True, help_text='Deal title', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Deal start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Deal end date', null=True)),
                ('signed_date', models.DateField(blank=True, help_text='Date when contract was signed', null=True)),
                ('fee_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deal value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency', max_length=3)),
                ('payment_terms', models.CharField(choices=[('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days'), ('advance_50', '50% Advance + 50% on Delivery'), ('advance_30', '30% Advance + 70% on Delivery'), ('milestone', 'Milestone-Based'), ('on_delivery', 'On Delivery'), ('custom', 'Custom Terms')], default='net_30', help_text='Payment terms', max_length=20)),
                ('deal_status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status of the deal', max_length=20)),
                ('brand_safety_score', models.IntegerField(blank=True, help_text='Brand safety score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('contract_file', models.FileField(blank=True, help_text='Signed contract file', null=True, upload_to='deals/contracts/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Brand or agency', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='identity.entity')),
                ('created_by', models.ForeignKey(help_text='User who created this deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department this deal belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='api.department')),
                ('deliverable_pack', models.ForeignKey(blank=True, help_text='Deliverable pack template used (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='artist_sales.deliverablepack')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main Artist'), ('featured', 'Featured'), ('guest', 'Guest'), ('ensemble', 'Ensemble')], default='main', help_text='Artist role in this deal', max_length=20)),
                ('artist_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Artist fee for this deal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('revenue_share_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue share percentage (for performance-based deals)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('contract_status', models.CharField(choices=[('pending', 'Pending Signature'), ('signed', 'Signed'), ('active', 'Active')], default='pending', help_text='Artist contract status', max_length=20)),
                ('signed_date', models.DateField(blank=True, help_text='Date when artist signed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='Artist entity', limit_choices_to={'entity_roles__role': 'artist'}, on_delete=django.db.models.deletion.PROTECT, related_name='artist_deals', to='identity.entity')),
                ('deal', models.ForeignKey(help_text='Deal', on_delete=django.db.models.deletion.CASCADE, related_name='deal_artists', to='artist_sales.deal')),
            ],
            options={
                'verbose_name': 'Deal Artist',
                'verbose_name_plural': 'Deal Artists',
                'ordering': ['role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('ig_post', 'Instagram Post'), ('ig_story', 'Instagram Story'), ('ig_reel', 'Instagram Reel'), ('tiktok_video', 'TikTok Video'), ('youtube_video', 'YouTube Video'), ('youtube_short', 'YouTube Short'), ('tvc', 'TV Commercial'), ('radio_spot', 'Radio Spot'), ('event', 'Event Appearance'), ('ooh', 'Out of Home (OOH)'), ('billboard', 'Billboard'), ('packaging', 'Product Packaging'), ('print_ad', 'Print Advertisement'), ('digital_banner', 'Digital Banner'), ('podcast', 'Podcast'), ('livestream', 'Livestream'), ('other', 'Other')], help_text='Type of deliverable', max_length=50)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('due_date', models.DateField(blank=True, help_text='Due date', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed')], db_index=True, default='planned', help_text='Current status', max_length=20)),
                ('asset_url', models.URLField(blank=True, help_text='URL to asset (S3, Google Drive, etc.)', max_length=500)),
                ('kpi_target', models.JSONField(blank=True, default=dict, help_text='Target KPIs (e.g., {views: 100000, engagement_rate: 0.05})')),
                ('kpi_actual', models.JSONField(blank=True, default=dict, help_text='Actual KPIs achieved')),
                ('cost_center', models.CharField(blank=True, help_text='Internal cost center code', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(help_text='Deal', on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='artist_sales.deal')),
            ],
            options={
                'verbose_name': 'Deal Deliverable',
                'verbose_name_plural': 'Deal Deliverables',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('concept', 'Concept'), ('script', 'Script'), ('storyboard', 'Storyboard'), ('rough_cut', 'Rough Cut'), ('final_cut', 'Final Cut'), ('caption', 'Caption/Copy'), ('static_kv', 'Static Key Visual'), ('usage_extension', 'Usage Extension Request'), ('other', 'Other')], help_text='Approval stage', max_length=20)),
                ('version', models.IntegerField(default=1, help_text='Version number for this stage')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When submitted for approval')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When approved/rejected', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Approval status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Approval notes/feedback')),
                ('file_url', models.FileField(blank=True, help_text='File to be approved', null=True, upload_to='approvals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_contact', models.ForeignKey(blank=True, help_text='Client-side approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to='identity.contactperson')),
                ('approver_user', models.ForeignKey(blank=True, help_text='Internal approver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(help_text='Deal', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='artist_sales.deal')),
                ('deliverable', models.ForeignKey(blank=True, help_text='Specific deliverable (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='artist_sales.dealdeliverable')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverablePackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('ig_post', 'Instagram Post'), ('ig_story', 'Instagram Story'), ('ig_reel', 'Instagram Reel'), ('tiktok_video', 'TikTok Video'), ('youtube_video', 'YouTube Video'), ('youtube_short', 'YouTube Short'), ('tvc', 'TV Commercial'), ('radio_spot', 'Radio Spot'), ('event', 'Event Appearance'), ('ooh', 'Out of Home (OOH)'), ('billboard', 'Billboard'), ('packaging', 'Product Packaging'), ('print_ad', 'Print Advertisement'), ('digital_banner', 'Digital Banner'), ('podcast', 'Podcast'), ('livestream', 'Livestream'), ('other', 'Other')], help_text='Type of deliverable', max_length=50)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this deliverable type', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(help_text='Deliverable pack', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='artist_sales.deliverablepack')),
            ],
            options={
                'verbose_name': 'Deliverable Pack Item',
                'verbose_name_plural': 'Deliverable Pack Items',
                'ordering': ['deliverable_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated invoice number', max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('advance', 'Advance Payment'), ('milestone', 'Milestone Payment'), ('final', 'Final Payment'), ('full', 'Full Payment')], default='full', help_text='Invoice type', max_length=20)),
                ('issue_date', models.DateField(help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent to Client'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Invoice status', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Date when payment was received', null=True)),
                ('pdf_url', models.FileField(blank=True, help_text='Invoice PDF file', null=True, upload_to='invoices/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(help_text='Deal', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='artist_sales.deal')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_name', models.CharField(db_index=True, help_text='Opportunity name', max_length=255)),
                ('stage', models.CharField(choices=[('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('shortlist', 'Artist Shortlist'), ('negotiation', 'Negotiation'), ('contract_sent', 'Contract Sent'), ('po_received', 'PO Received'), ('in_execution', 'In Execution'), ('completed', 'Completed'), ('closed_lost', 'Closed - Lost')], db_index=True, default='qualified', help_text='Current stage in sales pipeline', max_length=20)),
                ('amount_expected', models.DecimalField(blank=True, decimal_places=2, help_text='Expected deal value', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency', max_length=3)),
                ('probability_percent', models.IntegerField(default=10, help_text='Probability of closing (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, help_text='Expected closing date', null=True)),
                ('actual_close_date', models.DateField(blank=True, help_text='Actual closing date', null=True)),
                ('next_step', models.TextField(blank=True, help_text='Next action or milestone')),
                ('lost_reason', models.TextField(blank=True, help_text='Reason if opportunity was lost')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Brand or agency', on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='identity.entity')),
                ('brief', models.ForeignKey(blank=True, help_text='Original brief (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='artist_sales.brief')),
                ('created_by', models.ForeignKey(help_text='User who created this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department this opportunity belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='api.department')),
                ('owner_user', models.ForeignKey(help_text='Sales owner responsible for this opportunity', on_delete=django.db.models.deletion.PROTECT, related_name='opportunities_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='opportunity',
            field=models.ForeignKey(help_text='Opportunity that was won', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='artist_sales.opportunity'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1, help_text='Proposal version number')),
                ('fee_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross fee before discounts', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discounts', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('agency_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agency commission/fee', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net fee (gross - discounts - agency_fee)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', help_text='Currency', max_length=3)),
                ('proposal_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current status of the proposal', max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, help_text='When proposal was sent to client', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Proposal validity date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(help_text='Opportunity this proposal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='artist_sales.opportunity')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main Artist'), ('featured', 'Featured'), ('guest', 'Guest'), ('ensemble', 'Ensemble')], default='main', help_text='Artist role in this proposal', max_length=20)),
                ('proposed_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed artist fee', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(help_text='Artist entity', limit_choices_to={'entity_roles__role': 'artist'}, on_delete=django.db.models.deletion.PROTECT, related_name='artist_proposals', to='identity.entity')),
                ('proposal', models.ForeignKey(help_text='Proposal', on_delete=django.db.models.deletion.CASCADE, related_name='proposal_artists', to='artist_sales.proposal')),
            ],
            options={
                'verbose_name': 'Proposal Artist',
                'verbose_name_plural': 'Proposal Artists',
                'ordering': ['role', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='usage_terms',
            field=models.ForeignKey(blank=True, help_text='Usage terms and rights (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='artist_sales.usageterms'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['brief_status', 'created_at'], name='artist_sale_brief_s_646a79_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['account', 'brief_status'], name='artist_sale_account_01f8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['department', 'brief_status'], name='artist_sale_departm_317da4_idx'),
        ),
        migrations.AddIndex(
            model_name='brief',
            index=models.Index(fields=['sla_due_date'], name='artist_sale_sla_due_fdbc3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealartist',
            unique_together={('deal', 'artist')},
        ),
        migrations.AddIndex(
            model_name='dealdeliverable',
            index=models.Index(fields=['deal', 'status'], name='artist_sale_deal_id_fd25b4_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdeliverable',
            index=models.Index(fields=['due_date'], name='artist_sale_due_dat_0daa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='dealdeliverable',
            index=models.Index(fields=['status', 'due_date'], name='artist_sale_status_c3e1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['deal', 'status'], name='artist_sale_deal_id_f559a3_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['deliverable', 'stage'], name='artist_sale_deliver_cbc5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'submitted_at'], name='artist_sale_status_fdcd23_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deal', 'status'], name='artist_sale_deal_id_39634e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='artist_sale_status_6ab7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='artist_sale_issue_d_90ca05_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage', 'created_at'], name='artist_sale_stage_8a846a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['account', 'stage'], name='artist_sale_account_aafca0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner_user', 'stage'], name='artist_sale_owner_u_239c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['department', 'stage'], name='artist_sale_departm_782212_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='artist_sale_expecte_c1515a_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['opportunity', 'version'], name='artist_sale_opportu_2e6d34_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['proposal_status', 'created_at'], name='artist_sale_proposa_db4245_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('opportunity', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalartist',
            unique_together={('proposal', 'artist')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_status', 'created_at'], name='artist_sale_deal_st_90e782_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['account', 'deal_status'], name='artist_sale_account_fa3143_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['department', 'deal_status'], name='artist_sale_departm_e66df8_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['start_date'], name='artist_sale_start_d_b7523a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['end_date'], name='artist_sale_end_dat_240844_idx'),
        ),
    ]
