# Generated by Django 5.2.7 on 2025-11-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='file_url',
            field=models.URLField(blank=True, default='', help_text='URL to file for approval (Google Drive, Dropbox, etc.)', max_length=500),
        ),
    ]
