# Generated by Django 5.2.7 on 2025-10-27 22:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0008_add_social_media_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(db_index=True, help_text='Name of the campaign', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='Campaign value in currency', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('negotiation', 'Negotiation'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('lost', 'Lost')], db_index=True, default='lead', help_text='Current status of the campaign', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the campaign was confirmed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text="Artist entity (must have 'artist' role)", on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_artist', to='identity.entity')),
                ('brand', models.ForeignKey(help_text="Brand entity (must have 'brand' role)", on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_brand', to='identity.entity')),
                ('client', models.ForeignKey(help_text="Client entity (must have 'client' role)", on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_client', to='identity.entity')),
                ('created_by', models.ForeignKey(help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx'), models.Index(fields=['brand', 'status'], name='campaigns_c_brand_i_35002a_idx'), models.Index(fields=['client', 'status'], name='campaigns_c_client__6be06c_idx'), models.Index(fields=['artist', 'status'], name='campaigns_c_artist__73bbd7_idx')],
            },
        ),
    ]
