# Generated by Django 5.2.7 on 2025-10-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_is_client',
            field=models.BooleanField(default=False, help_text='True when the brand entity is the same as the client entity'),
        ),
        migrations.CreateModel(
            name='CampaignHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('support', 'Support'), ('observer', 'Observer')], default='support', help_text='Role of this handler in the campaign', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Handler',
                'verbose_name_plural': 'Campaign Handlers',
                'ordering': ['role', 'assigned_at'],
                'indexes': [models.Index(fields=['campaign', 'role'], name='campaigns_c_campaig_1ae638_idx'), models.Index(fields=['user', 'role'], name='campaigns_c_user_id_e7b1be_idx')],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
