# Generated by Django 5.2.7 on 2025-10-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_brand_is_client_campaignhandler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brand_is_client',
        ),
    ]
