# Generated by Django 5.2.7 on 2025-10-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_brand_is_client'),
        ('identity', '0009_contactperson_contactemail_contactphone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Primary contact person at the client for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='identity.contactperson'),
        ),
    ]
