# Generated by Django 5.2.7 on 2025-10-29 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_add_contact_person_to_campaign'),
        ('identity', '0011_alter_auditlogsensitive_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='department',
            field=models.CharField(choices=[('digital', 'Digital'), ('sales', 'Sales')], db_index=True, default='digital', help_text='Department this campaign belongs to (auto-set from creator)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['department', 'status'], name='campaigns_c_departm_193c63_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['department', 'created_at'], name='campaigns_c_departm_b9da7d_idx'),
        ),
    ]
