# Generated by Django 5.2.7 on 2025-10-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_department_role_and_more'),
        ('campaigns', '0005_campaign_department_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_c_departm_b59ac1_idx',
            old_name='campaigns_c_departm_193c63_idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_c_departm_2f8da4_idx',
            old_name='campaigns_c_departm_b9da7d_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='department',
            field=models.ForeignKey(help_text='Department this campaign belongs to (auto-set from creator)', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='api.department'),
        ),
    ]
