# Generated by Django 5.2.7 on 2025-10-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_departments_roles_users'),
        ('campaigns', '0006_rename_campaigns_c_departm_193c63_idx_campaigns_c_departm_b59ac1_idx_and_more'),
        ('catalog', '0001_initial'),
        ('identity', '0012_alter_sensitiveidentity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='song',
            field=models.ForeignKey(blank=True, help_text='Song/recording for this campaign (optional - use artist or song)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='catalog.recording'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='Artist entity (optional - use artist or song)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_artist', to='identity.entity'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(help_text='Brand entity (can be any business role entity)', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_brand', to='identity.entity'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(help_text='Client entity (can be any business role entity)', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns_as_client', to='identity.entity'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['song', 'status'], name='campaigns_c_song_id_4b9344_idx'),
        ),
    ]
