# Generated by Django 5.2.7 on 2025-10-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_seed_departments_roles_users'),
        ('campaigns', '0007_campaign_song_alter_campaign_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this campaign belongs to. If null, only admins can see it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='api.department'),
        ),
    ]
