# Generated by Django 5.2.7 on 2025-10-30 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_make_department_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated for this campaign', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_spent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget spent so far', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='client_health_score',
            field=models.IntegerField(blank=True, help_text='Client relationship health score (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency for all monetary values', max_length=3),
        ),
        migrations.AddField(
            model_name='campaign',
            name='department_data',
            field=models.JSONField(blank=True, default=dict, help_text='Department-specific data and metadata'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, help_text='Campaign end date', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='kpi_actuals',
            field=models.JSONField(blank=True, default=dict, help_text="Current/actual KPIs. Format: {'kpi_name': {'actual': value, 'unit': 'unit', 'last_updated': 'ISO datetime'}}"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='kpi_targets',
            field=models.JSONField(blank=True, default=dict, help_text="Target KPIs for the campaign. Format: {'kpi_name': {'target': value, 'unit': 'unit'}}"),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.CharField(blank=True, choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('tiktok', 'TikTok'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('amazon_music', 'Amazon Music'), ('soundcloud', 'SoundCloud'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('multi', 'Multi-Platform')], db_index=True, help_text='Primary platform for digital campaigns', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_type',
            field=models.CharField(blank=True, choices=[('ppc', 'PPC Campaign'), ('tiktok_ugc', 'TikTok UGC'), ('dsp_distribution', 'DSP Distribution'), ('radio_plugging', 'Radio Plugging'), ('playlist_pitching', 'Playlist Pitching'), ('youtube_cms', 'YouTube CMS'), ('social_media_mgmt', 'Social Media Management'), ('content_creation', 'Content Creation'), ('influencer_marketing', 'Influencer Marketing'), ('seo', 'SEO Optimization'), ('email_marketing', 'Email Marketing')], db_index=True, help_text='Type of service for digital campaigns', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, help_text='Campaign start date', null=True),
        ),
    ]
