# Generated by Django 5.2.7 on 2025-10-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_budget_allocated_campaign_budget_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='client_health_score',
        ),
    ]
