# Generated by Django 5.2.7 on 2025-10-31 05:24

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_client_profile_models'),
        ('campaigns', '0010_remove_client_health_score'),
        ('catalog', '0001_initial'),
        ('identity', '0015_add_client_profile_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='internal_cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated internal costs (labor, overhead, etc.)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='campaign',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('issued', 'Issued (Emisă)'), ('collected', 'Collected (Încasată)'), ('delayed', 'Delayed (Întârziată)')], db_index=True, help_text='Invoice status for this campaign', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated profit: value - budget_spent', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='campaigns_c_start_d_38d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'service_type'], name='campaigns_c_start_d_34748f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['invoice_status', 'start_date'], name='campaigns_c_invoice_f4e911_idx'),
        ),
    ]
