# Generated by Django 5.2.7 on 2025-10-31 08:43

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_to_arrays(apps, schema_editor):
    """Migrate existing single values to arrays"""
    Campaign = apps.get_model('campaigns', 'Campaign')

    for campaign in Campaign.objects.all():
        # Migrate service_type to service_types
        if hasattr(campaign, 'service_type_old') and campaign.service_type_old:
            campaign.service_types = [campaign.service_type_old]
        else:
            campaign.service_types = []

        # Migrate platform to platforms
        if hasattr(campaign, 'platform_old') and campaign.platform_old:
            campaign.platforms = [campaign.platform_old]
        else:
            campaign.platforms = []

        campaign.save(update_fields=['service_types', 'platforms'])


def reverse_migration(apps, schema_editor):
    """Convert arrays back to single values (reverse migration)"""
    Campaign = apps.get_model('campaigns', 'Campaign')

    for campaign in Campaign.objects.all():
        # Take first value from array or empty string
        if campaign.service_types:
            campaign.service_type_old = campaign.service_types[0]
        else:
            campaign.service_type_old = ''

        if campaign.platforms:
            campaign.platform_old = campaign.platforms[0]
        else:
            campaign.platform_old = ''

        campaign.save(update_fields=['service_type_old', 'platform_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_internal_cost_estimate_and_more'),
    ]

    operations = [
        # Remove the index that references the old field
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_start_d_34748f_idx',
        ),

        # Step 1: Rename old fields to temporary names
        migrations.RenameField(
            model_name='campaign',
            old_name='platform',
            new_name='platform_old',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='service_type',
            new_name='service_type_old',
        ),

        # Step 2: Add new array fields
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('meta', 'Meta (Facebook/Instagram)'),
                        ('google', 'Google Ads'),
                        ('tiktok', 'TikTok'),
                        ('spotify', 'Spotify'),
                        ('youtube', 'YouTube'),
                        ('apple_music', 'Apple Music'),
                        ('deezer', 'Deezer'),
                        ('amazon_music', 'Amazon Music'),
                        ('soundcloud', 'SoundCloud'),
                        ('twitter', 'Twitter/X'),
                        ('linkedin', 'LinkedIn'),
                        ('snapchat', 'Snapchat'),
                        ('pinterest', 'Pinterest'),
                        ('multi', 'Multi-Platform')
                    ],
                    max_length=50
                ),
                blank=True,
                db_index=True,
                default=list,
                help_text='Platforms for this campaign',
                size=None
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_types',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('ppc', 'PPC Campaign'),
                        ('tiktok_ugc', 'TikTok UGC'),
                        ('dsp_distribution', 'DSP Distribution'),
                        ('radio_plugging', 'Radio Plugging'),
                        ('playlist_pitching', 'Playlist Pitching'),
                        ('youtube_cms', 'YouTube CMS'),
                        ('social_media_mgmt', 'Social Media Management'),
                        ('content_creation', 'Content Creation'),
                        ('influencer_marketing', 'Influencer Marketing'),
                        ('seo', 'SEO Optimization'),
                        ('email_marketing', 'Email Marketing')
                    ],
                    max_length=50
                ),
                blank=True,
                db_index=True,
                default=list,
                help_text='Types of services for this campaign',
                size=None
            ),
        ),

        # Step 3: Migrate data from old fields to new array fields
        migrations.RunPython(migrate_to_arrays, reverse_migration),

        # Step 4: Remove old temporary fields
        migrations.RemoveField(
            model_name='campaign',
            name='platform_old',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='service_type_old',
        ),
    ]
