# Generated by Django 5.2.7 on 2025-10-31 11:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_change_to_array_fields'),
    ]

    operations = [
        # Add pricing model field
        migrations.AddField(
            model_name='campaign',
            name='pricing_model',
            field=models.CharField(
                choices=[('service_fee', 'Service Fee'), ('revenue_share', 'Revenue Share')],
                default='service_fee',
                db_index=True,
                help_text='Pricing model: service_fee (client pays us) or revenue_share (we generate revenue and share)',
                max_length=20
            ),
        ),
        # Add revenue_generated field
        migrations.AddField(
            model_name='campaign',
            name='revenue_generated',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Total revenue generated (for revenue_share model)',
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]
            ),
        ),
        # Add partner_share_percentage field
        migrations.AddField(
            model_name='campaign',
            name='partner_share_percentage',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Percentage of revenue shared with partner (0.00-100.00, for revenue_share model)',
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00')),
                    django.core.validators.MaxValueValidator(Decimal('100.00'))
                ]
            ),
        ),
        # Update invoice_status to add 'not_issued' and set default
        migrations.AlterField(
            model_name='campaign',
            name='invoice_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('not_issued', 'Not Issued (Neemisă)'),
                    ('issued', 'Issued (Emisă)'),
                    ('collected', 'Collected (Încasată)'),
                    ('delayed', 'Delayed (Întârziată)')
                ],
                default='not_issued',
                db_index=True,
                help_text='Invoice status for this campaign',
                max_length=20
            ),
        ),
        # Add index for pricing_model queries
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['pricing_model', 'status'], name='campaigns_c_pricing_d8f3a1_idx'),
        ),
    ]
