# Generated by Django 5.2.7 on 2025-10-31 09:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_add_pricing_model_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_c_pricing_9d766c_idx',
            old_name='campaigns_c_pricing_d8f3a1_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='invoice_status',
            field=models.CharField(choices=[('not_issued', 'Not Issued (Neemisă)'), ('issued', 'Issued (Emisă)'), ('collected', 'Collected (Încasată)'), ('delayed', 'Delayed (Întârziată)')], db_index=True, default='not_issued', help_text='Invoice status for this campaign', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campaign value in currency (optional, depends on pricing model)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
