# Generated by Django 5.2.7 on 2025-11-03 21:59
# Modified to preserve data by using RenameModel instead of Create/Delete

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_make_value_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Rename the model
        migrations.RenameModel(
            old_name='CampaignHandler',
            new_name='CampaignAssignment',
        ),

        # Step 2: Change the related_name from 'handlers' to 'assignments'
        migrations.AlterField(
            model_name='campaignassignment',
            name='campaign',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',  # Changed from 'handlers'
                to='campaigns.campaign'
            ),
        ),

        # Step 3: Add the new assigned_by field
        migrations.AddField(
            model_name='campaignassignment',
            name='assigned_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who created this assignment',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # Step 4: Update verbose names
        migrations.AlterModelOptions(
            name='campaignassignment',
            options={
                'verbose_name': 'Campaign Assignment',
                'verbose_name_plural': 'Campaign Assignments',
                'ordering': ['role', 'assigned_at'],
            },
        ),

        # Step 5: Update help text for role field
        migrations.AlterField(
            model_name='campaignassignment',
            name='role',
            field=models.CharField(
                choices=[('lead', 'Lead'), ('support', 'Support'), ('observer', 'Observer')],
                default='support',
                help_text='Role of this user in the campaign',  # Changed from "handler"
                max_length=20
            ),
        ),
    ]
