# Generated by Django 5.2.7 on 2025-11-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_rename_campaignhandler_to_campaignassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignassignment',
            new_name='campaigns_c_campaig_bc4d6f_idx',
            old_name='campaigns_c_campaig_1ae638_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignassignment',
            new_name='campaigns_c_user_id_bdba38_idx',
            old_name='campaigns_c_user_id_e7b1be_idx',
        ),
    ]
