# Generated by Django 5.2.7 on 2025-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_rename_campaigns_c_campaig_1ae638_idx_campaigns_c_campaig_bc4d6f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('endorsement', 'Endorsement'),
                    ('post', 'Post'),
                    ('song', 'Song'),
                    ('sale', 'Sale')
                ],
                help_text='Type of campaign (optional)',
                max_length=20,
                null=True
            ),
        ),
    ]
