# Generated by Django 5.2.7 on 2025-10-30 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message text')),
                ('notification_type', models.CharField(choices=[('assignment', 'Assignment'), ('mention', 'Mention'), ('status_change', 'Status Change'), ('contract_signed', 'Contract Signed'), ('contract_created', 'Contract Created'), ('comment', 'Comment'), ('system', 'System')], db_index=True, default='system', help_text='Type of notification', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('action_url', models.CharField(blank=True, help_text='Frontend URL to navigate to when clicking notification', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
