# Generated by Django 5.2.7 on 2025-10-30 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_tomorrow_enabled', models.BooleanField(default=True, help_text='Receive alerts for tasks due tomorrow')),
                ('deadline_urgent_enabled', models.BooleanField(default=True, help_text='Receive alerts for tasks due in next few hours')),
                ('task_inactivity_enabled', models.BooleanField(default=True, help_text='Receive alerts for tasks without updates')),
                ('task_overdue_enabled', models.BooleanField(default=True, help_text='Receive alerts for overdue tasks')),
                ('campaign_ending_enabled', models.BooleanField(default=True, help_text='Receive alerts for campaigns ending soon')),
                ('urgent_deadline_hours', models.IntegerField(default=4, help_text='Hours before deadline to receive urgent alert (1-24)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('inactivity_days', models.IntegerField(default=7, help_text='Days without update to trigger inactivity alert (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('campaign_ending_days', models.IntegerField(default=7, help_text='Days before campaign end to receive alert (1-30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('quiet_hours', models.CharField(choices=[('none', 'No Quiet Hours'), ('evening', 'Evening (6 PM - 9 AM)'), ('night', 'Night (8 PM - 8 AM)'), ('weekend', 'Weekends'), ('custom', 'Custom Hours')], default='none', help_text='When to pause non-urgent notifications', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for custom quiet hours', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for custom quiet hours', null=True)),
                ('enable_daily_digest', models.BooleanField(default=False, help_text='Receive a daily digest instead of individual alerts')),
                ('digest_time', models.TimeField(default='09:00:00', help_text='Time to send daily digest (if enabled)')),
                ('mute_all_alerts', models.BooleanField(default=False, help_text='Temporarily mute all automated alerts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
