# Generated by Django 5.2.7 on 2025-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('mention', 'Mention'), ('status_change', 'Status Change'), ('contract_signed', 'Contract Signed'), ('contract_created', 'Contract Created'), ('comment', 'Comment'), ('entity_request', 'Entity Change Request'), ('system', 'System')], db_index=True, default='system', help_text='Type of notification', max_length=50),
        ),
    ]
