# Generated by Django 5.2.7 on 2025-11-10 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('identity', '0019_remove_entity_entity_name_trgm_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Camp name', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Camp start date (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Camp end date (optional)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current status of the camp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the camp was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the camp was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When the camp was soft-deleted (null = active)', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this camp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camps_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department managing this camp', on_delete=django.db.models.deletion.PROTECT, related_name='camps', to='api.department')),
            ],
            options={
                'verbose_name': 'Camp',
                'verbose_name_plural': 'Camps',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Studio name (e.g., 'Studio A', 'Mastering Room')", max_length=255)),
                ('location', models.CharField(blank=True, help_text="Studio location name (e.g., 'Abbey Road Studios')", max_length=255)),
                ('city', models.CharField(blank=True, help_text='City where studio is located', max_length=100)),
                ('country', models.CharField(blank=True, default='Romania', help_text='Country where studio is located', max_length=100)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, help_text='Total hours scheduled (e.g., 8.5)', max_digits=5, null=True)),
                ('sessions', models.IntegerField(blank=True, help_text='Number of sessions scheduled', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for sorting studios within camp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp', models.ForeignKey(help_text='Parent camp', on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='camps.camp')),
            ],
            options={
                'verbose_name': 'Camp Studio',
                'verbose_name_plural': 'Camp Studios',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampStudioArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=True, help_text='Is this artist internal (signed) or external (contractor)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(help_text='Artist entity', on_delete=django.db.models.deletion.PROTECT, related_name='camp_studios', to='identity.entity')),
                ('studio', models.ForeignKey(help_text='Studio this artist is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='studio_artists', to='camps.campstudio')),
            ],
            options={
                'verbose_name': 'Camp Studio Artist',
                'verbose_name_plural': 'Camp Studio Artists',
                'ordering': ['-is_internal', 'artist__display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='camp',
            index=models.Index(fields=['deleted_at'], name='camps_camp_deleted_3b056b_idx'),
        ),
        migrations.AddIndex(
            model_name='camp',
            index=models.Index(fields=['start_date'], name='camps_camp_start_d_8a6240_idx'),
        ),
        migrations.AddIndex(
            model_name='camp',
            index=models.Index(fields=['status'], name='camps_camp_status_339564_idx'),
        ),
        migrations.AddIndex(
            model_name='camp',
            index=models.Index(fields=['department', '-start_date'], name='camps_camp_departm_c1c692_idx'),
        ),
        migrations.AddIndex(
            model_name='campstudio',
            index=models.Index(fields=['camp', 'order'], name='camps_camps_camp_id_b864fb_idx'),
        ),
        migrations.AddIndex(
            model_name='campstudioartist',
            index=models.Index(fields=['studio', 'is_internal'], name='camps_camps_studio__1c23b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campstudioartist',
            unique_together={('studio', 'artist')},
        ),
    ]
