# Generated by Django 5.2.7 on 2025-11-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_api_userpro_role_9579a2_idx_api_userpro_role_id_4a16d0_idx_and_more'),
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department managing this camp (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camps', to='api.department'),
        ),
    ]
